[theme]
primaryColor = "#4A90E2"  # Blue for primary actions
backgroundColor = "#FFFFFF"  # Clean white background
secondaryBackgroundColor = "#F0F2F6"  # Light gray for secondary elements
textColor = "#262730"  # Dark gray for text
font = "sans serif"

[server]
runOnSave = true 